### ISSUE TITLE
createPerson without providing a start date fails

### ISSUE THREAD

**Issue by robere2** [rpitv/glimpse-api#50]
When you attempt to create a new Person using GraphQL, it responds with the following error:

```
{
  "errors": [
    {
      "message": "Unexpected error.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createPerson"
      ],
      "extensions": {
        "originalError": {
          "message": "\nInvalid `)).create()` invocation in\n/usr/src/app/src/CrudGenerator.ts:286:12\n\n  283 // Create the object. Permissions have already been checked by @Auth directives.\n  284 return await (<any>(\n  285     ctx.prisma[modelNameToPrismaDelegateMap[modelName]]\n→ 286 )).create({\n        data: {\n          name: 'Billy Wu',\n      +   start: DateTime,\n      ?   pronouns?: String | null,\n      ?   graduation?: DateTime | null,\n      ?   end?: DateTime | null,\n      ?   description?: String | null,\n      ?   blogPosts?: {\n      ?     create?: BlogPostCreateWithoutAuthorInput | BlogPostCreateWithoutAuthorInput | BlogPostUncheckedCreateWithoutAuthorInput | BlogPostUncheckedCreateWithoutAuthorInput,\n      ?     connectOrCreate?: BlogPostCreateOrConnectWithoutAuthorInput | BlogPostCreateOrConnectWithoutAuthorInput,\n      ?     createMany?: BlogPostCreateManyAuthorInputEnvelope,\n      ?     connect?: BlogPostWhereUniqueInput | BlogPostWhereUniqueInput\n      ?   },\n      ?   credits?: {\n      ?     create?: CreditCreateWithoutPersonInput | CreditCreateWithoutPersonInput | CreditUncheckedCreateWithoutPersonInput | CreditUncheckedCreateWithoutPersonInput,\n      ?     connectOrCreate?: CreditCreateOrConnectWithoutPersonInput | CreditCreateOrConnectWithoutPersonInput,\n      ?     createMany?: CreditCreateManyPersonInputEnvelope,\n      ?     connect?: CreditWhereUniqueInput | CreditWhereUniqueInput\n      ?   },\n      ?   images?: {\n      ?     create?: PersonImageCreateWithoutPersonInput | PersonImageCreateWithoutPersonInput | PersonImageUncheckedCreateWithoutPersonInput | PersonImageUncheckedCreateWithoutPersonInput,\n      ?     connectOrCreate?: PersonImageCreateOrConnectWithoutPersonInput | PersonImageCreateOrConnectWithoutPersonInput,\n      ?     createMany?: PersonImageCreateManyPersonInputEnvelope,\n      ?     connect?: PersonImageWhereUniqueInput | PersonImageWhereUniqueInput\n      ?   },\n      ?   roles?: {\n      ?     create?: RoleCreateWithoutPersonInput | RoleCreateWithoutPersonInput | RoleUncheckedCreateWithoutPersonInput | RoleUncheckedCreateWithoutPersonInput,\n      ?     connectOrCreate?: RoleCreateOrConnectWithoutPersonInput | RoleCreateOrConnectWithoutPersonInput,\n      ?     createMany?: RoleCreateManyPersonInputEnvelope,\n      ?     connect?: RoleWhereUniqueInput | RoleWhereUniqueInput\n      ?   },\n      ?   users?: {\n      ?     create?: UserCreateWithoutPersonInput | UserCreateWithoutPersonInput | UserUncheckedCreateWithoutPersonInput | UserUncheckedCreateWithoutPersonInput,\n      ?     connectOrCreate?: UserCreateOrConnectWithoutPersonInput | UserCreateOrConnectWithoutPersonInput,\n      ?     createMany?: UserCreateManyPersonInputEnvelope,\n      ?     connect?: UserWhereUniqueInput | UserWhereUniqueInput\n      ?   }\n        }\n      })\n\nArgument start for data.start is missing.\n\nNote: Lines with + are required, lines with ? are optional.\n",
          "stack": "Error: \nInvalid `)).create()` invocation in\n/usr/src/app/src/CrudGenerator.ts:286:12\n\n  283 // Create the object. Permissions have already been checked by @Auth directives.\n  284 return await (<any>(\n  285     ctx.prisma[modelNameToPrismaDelegateMap[modelName]]\n→ 286 )).create({\n        data: {\n          name: 'Billy Wu',\n      +   start: DateTime,\n      ?   pronouns?: String | null,\n      ?   graduation?: DateTime | null,\n      ?   end?: DateTime | null,\n      ?   description?: String | null,\n      ?   blogPosts?: {\n      ?     create?: BlogPostCreateWithoutAuthorInput | BlogPostCreateWithoutAuthorInput | BlogPostUncheckedCreateWithoutAuthorInput | BlogPostUncheckedCreateWithoutAuthorInput,\n      ?     connectOrCreate?: BlogPostCreateOrConnectWithoutAuthorInput | BlogPostCreateOrConnectWithoutAuthorInput,\n      ?     createMany?: BlogPostCreateManyAuthorInputEnvelope,\n      ?     connect?: BlogPostWhereUniqueInput | BlogPostWhereUniqueInput\n      ?   },\n      ?   credits?: {\n      ?     create?: CreditCreateWithoutPersonInput | CreditCreateWithoutPersonInput | CreditUncheckedCreateWithoutPersonInput | CreditUncheckedCreateWithoutPersonInput,\n      ?     connectOrCreate?: CreditCreateOrConnectWithoutPersonInput | CreditCreateOrConnectWithoutPersonInput,\n      ?     createMany?: CreditCreateManyPersonInputEnvelope,\n      ?     connect?: CreditWhereUniqueInput | CreditWhereUniqueInput\n      ?   },\n      ?   images?: {\n      ?     create?: PersonImageCreateWithoutPersonInput | PersonImageCreateWithoutPersonInput | PersonImageUncheckedCreateWithoutPersonInput | PersonImageUncheckedCreateWithoutPersonInput,\n      ?     connectOrCreate?: PersonImageCreateOrConnectWithoutPersonInput | PersonImageCreateOrConnectWithoutPersonInput,\n      ?     createMany?: PersonImageCreateManyPersonInputEnvelope,\n      ?     connect?: PersonImageWhereUniqueInput | PersonImageWhereUniqueInput\n      ?   },\n      ?   roles?: {\n      ?     create?: RoleCreateWithoutPersonInput | RoleCreateWithoutPersonInput | RoleUncheckedCreateWithoutPersonInput | RoleUncheckedCreateWithoutPersonInput,\n      ?     connectOrCreate?: RoleCreateOrConnectWithoutPersonInput | RoleCreateOrConnectWithoutPersonInput,\n      ?     createMany?: RoleCreateManyPersonInputEnvelope,\n      ?     connect?: RoleWhereUniqueInput | RoleWhereUniqueInput\n      ?   },\n      ?   users?: {\n      ?     create?: UserCreateWithoutPersonInput | UserCreateWithoutPersonInput | UserUncheckedCreateWithoutPersonInput | UserUncheckedCreateWithoutPersonInput,\n      ?     connectOrCreate?: UserCreateOrConnectWithoutPersonInput | UserCreateOrConnectWithoutPersonInput,\n      ?     createMany?: UserCreateManyPersonInputEnvelope,\n      ?     connect?: UserWhereUniqueInput | UserWhereUniqueInput\n      ?   }\n        }\n      })\n\nArgument start for data.start is missing.\n\nNote: Lines with + are required, lines with ? are optional.\n\n    at Document.validate (/usr/src/app/node_modules/@prisma/client/runtime/index.js:47823:20)\n    at PrismaClient._executeRequest (/usr/src/app/node_modules/@prisma/client/runtime/index.js:49972:17)\n    at consumer (/usr/src/app/node_modules/@prisma/client/runtime/index.js:49916:23)\n    at /usr/src/app/node_modules/@prisma/client/runtime/index.js:49920:76\n    at runInChildSpan (/usr/src/app/node_modules/@prisma/client/runtime/index.js:49133:12)\n    at /usr/src/app/node_modules/@prisma/client/runtime/index.js:49920:20\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at PrismaClient._request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:49919:86)\n    at /usr/src/app/node_modules/@prisma/client/runtime/index.js:46474:25\n    at _callback (/usr/src/app/node_modules/@prisma/client/runtime/index.js:46233:52)"
        }
      }
    }
  ],
  "data": null
}
```

Adding a `start` variable to the input resolves this issue, however the `start` variable is intended to be optional, defaulting to the current time.

**Comment by robere2** [comment]
Resolved by #57, which removed `start` and `end` from the `Person` data type. Instead, they are now based on the Person's roles.
